CREATE TABLE public.indicateur_fin_engagement (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	designation varchar(200) NULL,
	valeur_saisie varchar(200) NULL,
	idactivite int4 NULL,
	idcateg_rubrique int4 NULL,
	periode_annuel int4 NULL,
	periode_mensuel int4 NULL,
	"type" varchar NULL,
	CONSTRAINT indicateur_fin_engagement_unique UNIQUE (id)
);


CREATE TABLE public.indicateur_fin_engag_prev (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	designation varchar(200) NULL,
	valeur_saisie varchar(200) NULL,
	idactivite int4 NULL,
	idcateg_rubrique int4 NULL,
	periode_annuel int4 NULL,
	periode_mensuel int4 NULL,
	"type" varchar NULL,
	CONSTRAINT indicateur_fin_engag_prev_unique UNIQUE (id)
);

